# Pull requests only: set to true to add reviewers
addReviewers: false

# Pull requests and issues: set to true or author to add assignees
addAssignees: author

# Pull requests and issues: a list of assignees, overrides reviewers on pull requests if set
assignees:
  - cloudopsworks-dev

# Pull requests and issues: number of assignees to add
# Set to 0 to add all of the assignees.
# Pull requests use numberOfReviewers if unset; issues default to all assignees.
numberOfAssignees: 0

# Pull requests and issues: skip when the title includes any keyword
skipKeywords:
  - wip