name: 'Auto Assign'
on: pull_request

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: cloudopsworks/auto-assign@v3.0.1
